name: gosec
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  gosec:
    name: security scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: stable
      - name: Run Gosec Security Scanner
        uses: securego/gosec@424fc4cd9c82ea0fd6bee9cd49c2db2c3cc0c93f # v2.22.11
        with:
          args: "-no-fail -fmt json -out results.json ./..."

      - name: Check Gosec Results
        run: |
          FOUND=$(jq '.Stats.found // 0' results.json)
          echo "Gosec found $FOUND issue(s)"
          if [ "$FOUND" -gt 0 ]; then
            echo "‚ùå Security issues detected! Please fix them before merging."
            exit 1
          else
            echo "‚úÖ No security issues found."
          fi

      - name: Run zizmor üåà
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
        with:
          inputs: .
          fail_on_error: true
